# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GB24Rpk3Wxohlg0kItPFUtyvKyCD697R
"""

import csv
data = []

# Function to clean the data and re-write the same csv file without null values
def clean_missing(file):
  # Read the csv file and get the clean data in a list
  with open(file) as csvfile:
      readCSV = csv.reader(csvfile, delimiter=',')
      for row in readCSV:
          if row[3] == "" :
            continue
          data.append(row)
  # Re-write the csv file with only the clean values
  with open(file, 'w') as writeFile:
      writer = csv.writer(writeFile)
      writer.writerows(data)

# Call of the function
clean_missing("/content/test.csv")