# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GB24Rpk3Wxohlg0kItPFUtyvKyCD697R
"""

import csv
data = []

# Function to clean the data and re-write the same csv file without null values
def count_missing(file):
  # Read the csv file and get the missing data in a list
  with open(file) as csvfile:
      readCSV = csv.reader(csvfile, delimiter=',')
      for row in readCSV:
          if row[3] == "" :
            data.append(row)
            

  print("Rows with missing charttime = " + str(len(data)))
  # Return the list of rows with missing charttime
  return data 

# Call of the function and save the list of rows missing data in a variable
missing_data = count_missing("/content/test.csv")